### ISSUE TITLE
Where is the Chrome.crx or how to compile?

### ISSUE THREAD

**Issue by Braunson** [bahlo/spockhub#2]
Where is the Chrome.crx or how to compile? Some additional documentation would be handy :)

**Comment by bahlo** [comment]
You can download the latest chrome extension from here: [v0.2.0](https://github.com/bahlo/spockhub/releases/tag/v0.2.0)

Just drag it into your extensions site to install.

**Comment by Braunson** [comment]
:+1: Forgot to check releases!
